
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Nov 22 11:44:22 CST 2018
//----------------------------------------------------

package minicsharpanalyzer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int nulll = 8;
  public static final int thiss = 9;
  public static final int brackets = 56;
  public static final int plus = 33;
  public static final int readline = 22;
  public static final int minus = 34;
  public static final int BoolConstant = 59;
  public static final int percentage = 37;
  public static final int IntegerConstant = 58;
  public static final int doublee = 53;
  public static final int dotcomma = 31;
  public static final int comma = 26;
  public static final int interfacee = 7;
  public static final int setBytee = 25;
  public static final int clasps = 51;
  public static final int extendss = 10;
  public static final int intt = 52;
  public static final int classs = 6;
  public static final int getBytee = 24;
  public static final int smallerEquals = 39;
  public static final int bracketsecond = 30;
  public static final int elsee = 15;
  public static final int notequals = 43;
  public static final int neww = 18;
  public static final int assignment = 32;
  public static final int newarray = 19;
  public static final int voidd = 5;
  public static final int parentesis = 47;
  public static final int returnn = 16;
  public static final int includee = 60;
  public static final int constt = 63;
  public static final int claspfirst = 49;
  public static final int iff = 14;
  public static final int greaterEquals = 41;
  public static final int EOF = 0;
  public static final int implementss = 11;
  public static final int booll = 54;
  public static final int whilee = 13;
  public static final int error = 1;
  public static final int equals = 42;
  public static final int times = 35;
  public static final int readinteger = 21;
  public static final int breakk = 17;
  public static final int or = 45;
  public static final int parentesisfirst = 27;
  public static final int forr = 12;
  public static final int stringg = 55;
  public static final int point = 48;
  public static final int bracketfirst = 29;
  public static final int smaller = 38;
  public static final int greater = 40;
  public static final int numerall = 61;
  public static final int DoubleConstant = 3;
  public static final int claspsecond = 50;
  public static final int not = 46;
  public static final int and = 44;
  public static final int parentesissecond = 28;
  public static final int Identifierr = 2;
  public static final int printt = 20;
  public static final int fileNamee = 62;
  public static final int notfound = 57;
  public static final int div = 36;
  public static final int mallocc = 23;
  public static final int StringConstant = 4;
}

